# ==============================
# SERVER
# ==============================
server.port=9000
spring.application.name=api-gateway

# ==============================
# EUREKA CONFIG
# ==============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# ==============================
# GATEWAY ROUTES
# ==============================

# Identity Service
spring.cloud.gateway.routes[0].id=identity-service
spring.cloud.gateway.routes[0].uri=lb://identity-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Banking Service
spring.cloud.gateway.routes[1].id=banking-service
spring.cloud.gateway.routes[1].uri=lb://banking-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/accounts/**


# Loan Service
spring.cloud.gateway.routes[2].id=loan-service
spring.cloud.gateway.routes[2].uri=lb://loan-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/loans/**
# ==============================
# DISCOVERY (IMPORTANT)
# ==============================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ==============================
# DEBUG (Optional but useful)
# ==============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG